run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  enable:
    - govet
    - staticcheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple